version: 2

build:
   image: latest

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: aiida-core/docs/source/conf.py

# Need to install the package itself such that the entry points are installed and the API doc can build properly
python:
    version: 3.8
    install:
        - method: pip
          path: ./aiida-core
          extra_requirements:
            - docs
            - tests

