version: 2

# Important: we need to disable all unneeded formats.
# Note that HTML and JSON are always built: https://docs.readthedocs.io/en/latest/yaml-config.html#formats
# Especially, the 'htmlzip' format takes a LOT of memory and causes the build to fail - see our issue #1472:
# https://github.com/aiidateam/aiida-core/issues/1472
formats: []

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - ln -s -r ./locales aiida-core/docs/source/locales

# Need to install the package itself such that the entry points are installed and the API doc can build properly
python:
    install:
        - method: pip
          path: aiida-core
          extra_requirements:
            - docs
            - tests
            - rest
            - atomic_tools

# Let the build fail if there are any warnings
sphinx:
    builder: html
    fail_on_warning: false

search:
  ranking:
    reference/apidoc/*: -7

submodules:
  include: all