version: 2

build:
   image: latest

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: aiida_core/docs/source/conf.py

# Need to install the package itself such that the entry points are installed and the API doc can build properly
python:
    version: 3.8
    install:
        - method: pip
          path: ./aiida_core
          extra_requirements:
            - docs
            - tests
        
# By default readthedocs does not checkout git submodules
submodules:
    include: all
    recursive: true
