# Usage: conda env create -n myenvname -f environment.yml
---
name: readthedocs
channels:
- conda-forge
- defaults
dependencies:
- aiida-core~=1.6
- sphinx~=3.2.1
- pygments~=2.5
- pip>=20.1  # pip is needed as dependency
- pip:
  - transifex-client~=0.14
  - pydata-sphinx-theme~=0.4.0
  - sphinxcontrib-details-directive~=0.1.0
  - sphinx-panels~=0.5.0
  - sphinx-copybutton~=0.3.0
  - sphinx-notfound-page~=0.5
  - sphinxext-rediraffe~=0.2.4
  - ./aiida_core[tests,docs]