name: Auto Translate

# Run this workflow every month on the first day of the month, or manually
# It will fetch the latest translations from Transifex, run the translation script, and open a PR.
# Once the PR is merged, the translations will be synced to Transifex.

on:
  schedule:
    - cron: "0 0 27,13 * *"
  workflow_dispatch:
  
jobs:
  auto-translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tx client
        run: |
          curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash -s -- v1.6.9
          mv tx /usr/local/bin/tx

      - name: Fetch latest PO files from Transifex
        # -a: --all: Fetch all translation files
        # -t: pull translations
        # -f: regardless of timestamp
        run: |
          tx pull -a -t -f
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}

      - name: Set characters limit base on event
        id: set-limit
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "CHR_LIMIT=1000" >> $GITHUB_OUTPUT
          else;
            # otherwise use 80% of the api limit
            CHR_LIMIT=$(aiida-core-i18n status -p avail | awk '{print int($1*0.4)}')
            echo "Limiting to $CHR_LIMIT characters"
            echo "CHR_LIMIT=$CHR_LIMIT" >> $GITHUB_OUTPUT
          fi
        env:
          DEEPL_TOKEN: ${{ secrets.DEEPL_TOKEN }}

      - name: Run translation script
        run: |
          python .github/scripts/translate.py --limit ${{ steps.set-limit.outputs.CHR_LIMIT }}} translations/zh_CN/
        env:
          DEEPL_TOKEN: ${{ secrets.DEEPL_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto-translate PO files"
          branch: auto-translate-${{ github.sha }}
          title: "Auto-translate PO files"
          body: "This PR includes the latest translations from bot script."
          reviewers: unkcpz
          delete-branch: true
