name: Auto Translate

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
  
  
jobs:
  auto-translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tx client
        run: |
          curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash -s -- v1.6.9
          mv tx /usr/local/bin/tx

      - name: Fetch latest PO files from Transifex
        # -a: --all: Fetch all translation files
        # -t: pull translations
        # -f: regardless of timestamp
        run: |
          tx pull -a -t -f
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}

      - name: Run translation script
        run: |
          # Add your commands here to run the translation script
          # demo using: .github/demo-404.po
          cp .github/demo-404.po translations/zh_CN/404.po

      - name: Push PO files to Transifex
        # -t: push translations
        run: |
          tx push -t
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}

      - name: Pull again to sync metadata
        # -a: --all: Fetch all translation files
        # -t: pull translations
        # -f: regardless of timestamp
        run: |
          tx pull -a -t -f
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto-translate PO files"
          branch: auto-translate-${{ github.sha }}
          title: "Auto-translate PO files"
          body: "This PR includes the latest translations and sync from Transifex."
          reviewers: unkcpz
